### ISSUE TITLE
Проблемы в настройках pom.xml

### ISSUE THREAD

**Issue by TikhomirovSergey** [Den661/TinkoffTest#1]
1) Использование `maven-compiler-plugin`. Пример хороший, но все же это плохо, т.к. это будет работать только на одной машине WINDOWS. Вместо пути к исполняемому файлу использовать параметры `source` и `target`.

2) Зачем использовать `htmlelements-java 1.18`? Во-первых, этот артефакт в проекте не используется.
Во-вторых, Selenide 4.11.1 зависит от selenium 3.11, а htmlelements-java 1.18 зависит от selenium 3.5.1.  Это чревато конфликтом зависимостей и довольно странными ошибками.

**Comment by khinkaliSoul** [comment]
@TikhomirovSergey  замечания исправлены в https://github.com/Den661/TinkoffTest/commit/4702210500d9efa88b8d25a1b3780e2ab4a5727d
